insert into Brand (BrandName, Country, Description) values ('Lexus', 'China', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Brand (BrandName, Country, Description) values ('Lincoln', 'Norway', 'Cras non velit nec nisi vulputate nonummy.');
insert into Brand (BrandName, Country, Description) values ('Toyota', 'China', 'Quisque porta volutpat erat.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Dominican Republic', 'Etiam pretium iaculis justo.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Senegal', 'Nam tristique tortor eu pede.');
insert into Brand (BrandName, Country, Description) values ('GMC', 'Venezuela', 'Nullam molestie nibh in lectus.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'Slovenia', 'Vestibulum rutrum rutrum neque.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Indonesia', 'Etiam faucibus cursus urna.');
insert into Brand (BrandName, Country, Description) values ('BMW', 'France', 'Morbi porttitor lorem id ligula.');
insert into Brand (BrandName, Country, Description) values ('Hyundai', 'United Kingdom', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Brand (BrandName, Country, Description) values ('Suzuki', 'Norway', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Poland', 'In hac habitasse platea dictumst.');
insert into Brand (BrandName, Country, Description) values ('Nissan', 'United States', 'Sed ante.');
insert into Brand (BrandName, Country, Description) values ('Saab', 'Poland', 'Donec semper sapien a libero.');
insert into Brand (BrandName, Country, Description) values ('Isuzu', 'France', 'Phasellus id sapien in sapien iaculis congue.');
insert into Brand (BrandName, Country, Description) values ('Volkswagen', 'China', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into Brand (BrandName, Country, Description) values ('Land Rover', 'United States', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Brand (BrandName, Country, Description) values ('Volkswagen', 'Russia', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Poland', 'Vestibulum sed magna at nunc commodo placerat.');
insert into Brand (BrandName, Country, Description) values ('Hyundai', 'Canada', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Brand (BrandName, Country, Description) values ('Volkswagen', 'Brazil', 'Curabitur at ipsum ac tellus semper interdum.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'Brazil', 'Praesent lectus.');
insert into Brand (BrandName, Country, Description) values ('Lamborghini', 'Peru', 'Phasellus in felis.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Spain', 'Nulla tellus.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'Uganda', 'Suspendisse accumsan tortor quis turpis.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'China', 'Sed accumsan felis.');
insert into Brand (BrandName, Country, Description) values ('Toyota', 'Indonesia', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Brand (BrandName, Country, Description) values ('Chrysler', 'Ireland', 'Nunc nisl.');
insert into Brand (BrandName, Country, Description) values ('Porsche', 'China', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Brand (BrandName, Country, Description) values ('GMC', 'Peru', 'Quisque ut erat.');
insert into Brand (BrandName, Country, Description) values ('Mitsubishi', 'Philippines', 'Maecenas rhoncus aliquam lacus.');
insert into Brand (BrandName, Country, Description) values ('Dodge', 'Brazil', 'Mauris sit amet eros.');
insert into Brand (BrandName, Country, Description) values ('Volvo', 'Guatemala', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into Brand (BrandName, Country, Description) values ('Oldsmobile', 'China', 'Cras in purus eu magna vulputate luctus.');
insert into Brand (BrandName, Country, Description) values ('Ford', 'Poland', 'Suspendisse potenti.');
insert into Brand (BrandName, Country, Description) values ('Nissan', 'Croatia', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Brand (BrandName, Country, Description) values ('Volkswagen', 'China', 'In eleifend quam a odio.');
insert into Brand (BrandName, Country, Description) values ('Toyota', 'Philippines', 'Morbi non quam nec dui luctus rutrum.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'Azerbaijan', 'Nullam molestie nibh in lectus.');
insert into Brand (BrandName, Country, Description) values ('Chevrolet', 'Greece', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
